### ISSUE TITLE
Manjaro/Arch Linux Help

### ISSUE THREAD

**Issue by F3TTT** [MichaelJCole/bithammer#11]
I'm running this in a VM, so that may be the problem.  Not sure if you can pull off ARP cache poisoning without raw device access.  

Anyhow, I installed scapy with "yaourt scapy" and already had the other components installed.  Here is what I'm getting:

[danieljdoughty@manjaro-vm bithammer]$ sudo python ./bithammer 
[sudo] password for danieljdoughty: 
  File "./bithammer", line 57
    print "Finding network gateway ..."
                                      ^
SyntaxError: Missing parentheses in call to 'print'
[danieljdoughty@manjaro-vm bithammer]$

**Comment by zielu** [comment]
Hi, just run into this: 
sudo **python2** ./bithammer

calls correct python interpreter

**Comment by F3TTT** [comment]
Confirmed, thanks for the help!

[danieljdoughty@manjaro-vm bithammer]$ sudo python2 ./bithammer
Starting BitHammer.
^CTraceback (most recent call last):
  File "./bithammer", line 187, in <module>
    bh.hammer()
  File "./bithammer", line 179, in hammer
    time.sleep(self.DELAY)
KeyboardInterrupt
[danieljdoughty@manjaro-vm bithammer]$
